export const COURSES_FETCHED = "COURSES_FETCHED";
export const COURSES_EMPTY = "COURSES_EMPTY";
export const COURSES_INCREMENT = "COURSES_INCREMENT";
export const LEAVE_COURSE = "LEAVE_COURSE";

export const COURSE_FETCHED = "COURSE_FETCHED";
export const COURSE_EMPTY = "COURSE_EMPTY";
export const COURSE_UPDATE = "COURSE_UPDATE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const USER_EMPTY = "USER_EMPTY";
export const USER_FETCHED = "USER_FETCHED";
export const USER_UPDATE = "USER_UPDATE";
